In [1]:
import numpy as np

In [2]:
a = np.arange(100,200)

In [3]:
a

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [4]:
b = a.reshape(10,10)

In [5]:
b

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])

In [6]:
a.size

100

In [7]:
b.size

100

In [8]:
b.shape

(10, 10)

In [10]:
a.shape

(100,)

In [11]:
a.ndim

1

In [12]:
b.ndim

2

In [13]:
c = a.reshape(25,4)

In [14]:
c

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111],
       [112, 113, 114, 115],
       [116, 117, 118, 119],
       [120, 121, 122, 123],
       [124, 125, 126, 127],
       [128, 129, 130, 131],
       [132, 133, 134, 135],
       [136, 137, 138, 139],
       [140, 141, 142, 143],
       [144, 145, 146, 147],
       [148, 149, 150, 151],
       [152, 153, 154, 155],
       [156, 157, 158, 159],
       [160, 161, 162, 163],
       [164, 165, 166, 167],
       [168, 169, 170, 171],
       [172, 173, 174, 175],
       [176, 177, 178, 179],
       [180, 181, 182, 183],
       [184, 185, 186, 187],
       [188, 189, 190, 191],
       [192, 193, 194, 195],
       [196, 197, 198, 199]])

In [15]:
a.reshape(4,25)

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137,
        138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
        163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174],
       [175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187,
        188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])

In [18]:
a = np.random.randint(200,400,(5,5))

In [19]:
a

array([[344, 389, 209, 265, 328],
       [293, 217, 320, 343, 301],
       [372, 367, 303, 352, 278],
       [370, 256, 369, 353, 243],
       [364, 348, 289, 387, 338]])

In [20]:
# accessing array elements

In [21]:
a[1]

array([293, 217, 320, 343, 301])

In [22]:
a[1][1]

217

In [23]:
a[:,0]

array([344, 293, 372, 370, 364])

In [24]:
a[1:4,2:]

array([[320, 343, 301],
       [303, 352, 278],
       [369, 353, 243]])

In [25]:
a

array([[344, 389, 209, 265, 328],
       [293, 217, 320, 343, 301],
       [372, 367, 303, 352, 278],
       [370, 256, 369, 353, 243],
       [364, 348, 289, 387, 338]])

In [26]:
#applying conditions on arrays

In [27]:
a > 250

array([[ True,  True, False,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True]])

In [28]:
# replace elements in an array

In [29]:
ar1 = np.arange(1,20)

In [30]:
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [31]:
# replace all even numbers with zero

In [32]:
res = np.where(ar1%2==0,0,ar1)

In [33]:
res

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0, 17,
        0, 19])

In [34]:
ar2 = np.array([10,23,10,34,56,10,45,10])

In [35]:
ar2

array([10, 23, 10, 34, 56, 10, 45, 10])

In [36]:
a = np.arange(0,100,10)

In [37]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
a[3]

30

In [39]:
np.put(a,[0,3,5],[100,200,300])

In [40]:
a

array([100,  10,  20, 200,  40, 300,  60,  70,  80,  90])

In [41]:
np.put(a,[0,3,5],[100])

In [42]:
a

array([100,  10,  20, 100,  40, 100,  60,  70,  80,  90])

In [43]:
# missing values in an array

In [44]:
a= np.array([10,np.nan,30,np.nan,34,67,89,np.nan])

In [45]:
a

array([10., nan, 30., nan, 34., 67., 89., nan])

In [46]:
np.isnan(a)

array([False,  True, False,  True, False, False, False,  True])

In [47]:
a

array([10., nan, 30., nan, 34., 67., 89., nan])

In [48]:
np.where(np.isnan(a))

(array([1, 3, 7], dtype=int64),)

In [49]:
a[np.where(np.isnan(a))]=100

In [50]:
a

array([ 10., 100.,  30., 100.,  34.,  67.,  89., 100.])

In [51]:
a = np.arange(10,40)

In [52]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [54]:
np.isnan(a).any()

False

In [55]:
b = np.array([10,np.nan])

In [56]:
np.isnan(b).any()

True

In [57]:
# stack arrays horizontally

In [65]:
a = np.arange(10,20).reshape(2,5)

In [66]:
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [63]:
b = np.arange(20,30).reshape(2,5)

In [64]:
b

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [67]:
np.hstack([a,b])

array([[10, 11, 12, 13, 14, 20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19, 25, 26, 27, 28, 29]])

In [68]:
# stack arrays vertically

In [69]:
np.vstack([a,b])

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [70]:
# process elements on a condition

In [73]:
a = np.array([23,45,67,89])
b = np.array([23,56,78,10])

In [74]:
np.where(a==b)

(array([0], dtype=int64),)

In [75]:
a = np.arange(0,60)

In [76]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [78]:
np.where((a>20) & (a<35))

(array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34],
       dtype=int64),)

In [79]:
# check elements in an array using isin() method

In [80]:
np.isin(a,[37])

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [81]:
np.isin(a,[37,47])

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [82]:
a = np.arange(0,10)

In [83]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [85]:
a = np.arange(0,20).reshape(4,5)

In [86]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [87]:
a[::-1]

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [88]:
a[:,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

In [89]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [90]:
a[:,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

In [91]:
a[::-1,]

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [92]:
a[::-1,::-1] 

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])