In [2]:
import numpy as np

In [3]:
# creating a numpy array

In [4]:
a = np.array([12,34,56,78,90,12])

In [5]:
a

array([12, 34, 56, 78, 90, 12])

In [6]:
type(a)

numpy.ndarray

In [7]:
b = [34,56,78,12,45,56]
c = np.array(b) # converting a list into an array

In [8]:
c

array([34, 56, 78, 12, 45, 56])

In [9]:
a

array([12, 34, 56, 78, 90, 12])

In [10]:
# memory address of an array
a.data

In [11]:
#type of an array
type(a)

numpy.ndarray

In [13]:
#datatype of an array
a.dtype

dtype('int32')

In [14]:
# convert integer array into floating array
a.astype(float)

array([12., 34., 56., 78., 90., 12.])

In [15]:
# arange()- it generates evenly spaced elements in given range
# generate evenly spaced elements between 10 to 20 with space 1

In [16]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [18]:
#generate evenly spaced elements from 100 to 10 in descending order with space -10

In [19]:
np.arange(100,10,-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [20]:
a

array([12, 34, 56, 78, 90, 12])

In [22]:
a.itemsize #returns no.of bytes occupied by each element

4

In [23]:
a.nbytes #total no.of bytes occupied by an array

24

In [24]:
np.zeros(10) # returns zeros array of 10 elements

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
x = np.zeros([4,5])

In [28]:
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
type(x)

numpy.ndarray

In [31]:
x.size

20

In [32]:
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
len(x)

4

In [34]:
x.shape

(4, 5)

In [35]:
x.ndim

2

In [36]:
a = np.array([12,34,56,78,90,13])

In [37]:
a

array([12, 34, 56, 78, 90, 13])

In [38]:
a.ndim # returns the dimensions of an array

1

In [39]:
# creating 2d array

In [40]:
b = np.array([[12,34],[23,45],[56,78]])

In [41]:
b

array([[12, 34],
       [23, 45],
       [56, 78]])

In [42]:
b.ndim

2

In [43]:
# creating ones array
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
# repeat()- repeats an item in an array

In [46]:
np.repeat(10,5)

array([10, 10, 10, 10, 10])

In [47]:
a = np.array([10,20,30])

In [48]:
np.repeat(a,3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [49]:
a = np.arange(1,50)

In [50]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [51]:
a[a%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [52]:
b = np.arange(20,70)

In [53]:
b[b%2==0]

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60, 62, 64, 66, 68])

In [54]:
#linspace()- it returns linearly spaced elements in a given range

In [55]:
np.linspace(10,20,4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [56]:
np.linspace(1,100,20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [57]:
# s
sum()- returns sum of an array

In [59]:
a = np.array([12,34,56,78,12,34])

In [60]:
a.sum()

226

In [61]:
a = np.arange(100,200)
a[a%2==0].sum()

7450

In [64]:
a = np.arange(1,100)
b= a[a%2==1]
b.sum()/len(b)

50.0

In [65]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [66]:
a.sum()

4950

In [67]:
a.cumsum()

array([   1,    3,    6,   10,   15,   21,   28,   36,   45,   55,   66,
         78,   91,  105,  120,  136,  153,  171,  190,  210,  231,  253,
        276,  300,  325,  351,  378,  406,  435,  465,  496,  528,  561,
        595,  630,  666,  703,  741,  780,  820,  861,  903,  946,  990,
       1035, 1081, 1128, 1176, 1225, 1275, 1326, 1378, 1431, 1485, 1540,
       1596, 1653, 1711, 1770, 1830, 1891, 1953, 2016, 2080, 2145, 2211,
       2278, 2346, 2415, 2485, 2556, 2628, 2701, 2775, 2850, 2926, 3003,
       3081, 3160, 3240, 3321, 3403, 3486, 3570, 3655, 3741, 3828, 3916,
       4005, 4095, 4186, 4278, 4371, 4465, 4560, 4656, 4753, 4851, 4950],
      dtype=int32)

In [68]:
a = np.arange(1,10)

In [69]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a.sum()

45

In [71]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [72]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
L = [12,23,45,67,89,11]
L1 = []
summ = 0
for i in L:
    summ = summ+i
    L1.append(summ)
print(L1)
    

[12, 35, 80, 147, 236, 247]


In [74]:
a = np.arange(10,20)

In [75]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [76]:
a.cumsum()# returns cummulative sum

array([ 10,  21,  33,  46,  60,  75,  91, 108, 126, 145], dtype=int32)

In [78]:
# genarating random numbers
#random.random() - returns an array of random numbers in btw 0 -1

In [80]:
np.random.random(5)

array([0.82050212, 0.92022293, 0.53386559, 0.9272768 , 0.08116256])

In [81]:
a = np.random.random(20)

In [82]:
a

array([0.94755982, 0.83754101, 0.67599946, 0.09092911, 0.94496899,
       0.73017349, 0.28565973, 0.67107572, 0.23003787, 0.22733155,
       0.81075108, 0.62050451, 0.55230416, 0.78192983, 0.89677295,
       0.82388113, 0.0562895 , 0.49632426, 0.05558109, 0.84439634])

In [83]:
a.cumsum()

array([ 0.94755982,  1.78510083,  2.46110029,  2.5520294 ,  3.49699839,
        4.22717188,  4.51283162,  5.18390734,  5.41394521,  5.64127676,
        6.45202783,  7.07253235,  7.6248365 ,  8.40676633,  9.30353928,
       10.12742041, 10.18370991, 10.68003417, 10.73561525, 11.5800116 ])

In [84]:
np.random.seed(196)
np.random.random(5)

array([0.68950928, 0.57797539, 0.04968657, 0.1790961 , 0.50718443])

In [92]:
np.random.seed(12)
np.random.random(4)

array([0.15416284, 0.7400497 , 0.26331502, 0.53373939])

In [ ]:
#seed()-used to produce same random numbers on each run

In [93]:
# generate an array of random integers

In [94]:
#randint()-generates an array of random integers

In [99]:
np.random.seed(14440)
np.random.randint(10,500,10)

array([317,  79, 471, 136,  14,  72, 138, 229, 290, 253])

In [101]:
np.random.seed(5)
a = np.random.randint(200,600,100)
if 456 in a:
    print('yes')
else:
    print('no')

yes


In [103]:
a=int(input())
b=int(input())
c=int(input())
if a==b==c:
 print('all ages are same')
elif a>=b and a>=c:
 if (a==b) or(b==c) and b>=c:
  print('%d is eldest'%a)
  print('%d is youngest'%c)
 else:
  print('%d is eldest'%a)
  print('%d is youngest'%b)
elif b>=a and b>=c:
 if (a==b) or(b==c) and a>=c:
  print('%d is eldest'%b)
  print('%d is youngest'%c)
 else:
  print('%d is eldest'%b)
  print('%d is youngest'%a)
else:
 if (a==b) or(b==c) and b>=a:
  print('%d is eldest'%c)
  print('%d is youngest'%b)
 else:
  print('%d is eldest'%c)
  print('%d is youngest'%a)    
    
    

90
90
90
all ages are same


In [104]:
a = np.arange(1,20)

In [105]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [106]:
#max() -returns maximum number in an array

In [107]:
a.max()

19

In [108]:
a.min()

1

In [109]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [110]:
# generate 10 random numbers

In [111]:
a =np.random.random(10)

In [112]:
a

array([0.92668262, 0.91262676, 0.82481072, 0.09420273, 0.36104842,
       0.03550903, 0.54635835, 0.79614272, 0.0511428 , 0.18866774])

In [113]:
np.trunc(a)# truncates decimal part and retuns integer part only

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [114]:
np.floor(a)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [119]:
np.random.randn(50)

array([ 0.46770521,  0.10134479, -0.05935198, -2.38669774,  1.22217056,
       -0.81391201,  0.95626186, -0.63851056, -0.14312642, -0.22418983,
       -1.03849524, -0.17170905,  0.47634618, -0.41417827, -1.26408334,
       -0.57321556,  0.24981732,  1.14720208,  0.83594396,  0.28740365,
       -0.9955963 ,  0.90688947,  0.02421074, -0.23998173,  0.91011056,
        0.61784475,  0.49961804, -1.15154425, -0.6105164 , -1.70388541,
        0.19443738,  0.02824125,  0.93256051,  0.21204332, -0.36794457,
        2.1114884 , -1.02957349, -1.33628031, -0.61056736,  0.52469426,
       -0.34930813, -0.44073846, -1.1212876 ,  1.47284473, -0.62337224,
       -1.08070195, -0.12253009, -0.8077431 , -0.23255622,  1.33515034])

In [120]:
a

array([0.92668262, 0.91262676, 0.82481072, 0.09420273, 0.36104842,
       0.03550903, 0.54635835, 0.79614272, 0.0511428 , 0.18866774])

In [122]:
np.random.seed(5)
a = np.random.randint(100,200,30)

In [123]:
a

array([199, 178, 161, 116, 173, 108, 162, 127, 130, 180, 107, 176, 115,
       153, 180, 127, 144, 177, 175, 165, 147, 130, 184, 186, 118, 109,
       141, 162, 101, 182])

In [124]:
a.min()

101

In [125]:
a.argmin() # returns index of min value in an array

28

In [126]:
len(a)

30

In [127]:
#argmax()- returns index of max value in an array

In [128]:
a.argmax()

0

In [129]:
#mean()- returns mean of an array

In [130]:
a.mean()

150.43333333333334

In [132]:
np.median(a) # returns median value of an array

157.0

In [133]:
#mode()- frequntly occured item in an array

In [137]:
np.unique(a)

array([101, 107, 108, 109, 115, 116, 118, 127, 130, 141, 144, 147, 153,
       161, 162, 165, 173, 175, 176, 177, 178, 180, 182, 184, 186, 199])

In [140]:
a = np.array([10,34,10,20,34,10,20])

In [141]:
np.unique(a) # returns unique values in an array

array([10, 20, 34])

In [142]:
# create a 2dim array

In [143]:
a = np.array([[34,12,45],[12,11,22],[1,2,3]])

In [144]:
a

array([[34, 12, 45],
       [12, 11, 22],
       [ 1,  2,  3]])

In [145]:
a.sum()

142

In [146]:
a.sum(1) # row wise sum

array([91, 45,  6])

In [147]:
a.sum(0)#col wise sum

array([47, 25, 70])

In [148]:
a.sum(axis=1) # row wise sum

array([91, 45,  6])

In [149]:
a.sum(axis=0)# colwise sum

array([47, 25, 70])